### ISSUE TITLE
Add AUTHORS file

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/brand#16]
Let's add an authors file to this repository.

> > @Ainali . Excellent idea let's make a separate pull request for that

_Originally posted by @felixfaassen in https://github.com/publiccodenet/brand/pull/14#issuecomment-703533306_

**Comment by felixfaassen** [comment]
@Ainali  Looks fine to me. We might need to add specifics like  illustrations by :  music by ? but that could be a later iteration or we could leave it out entirely. Both choices are ok to me ;-)
