### ISSUE TITLE
Add a resource with templates?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/brand#5]
When I made the signs for the Open day I started off by creating a template for myself. I guess it would be useful to share it with others. Should I create a resource called Templates and add them there? And add a link to it from the list **Guidelines and assets** on the first page?

**Comment by bvhme** [comment]
Hey Jan, what is the format of these things?

And yes, feel free to make a section like that and add your things.

**Comment by Ainali** [comment]
I made them in Inkscape so svg is probably the best format to share them in. 

Good, I'll start working on it.

**Comment by Ainali** [comment]
closed by #7
