### ISSUE TITLE
Make a template for odt documents

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/brand#9]
This can be used to make nicely formatted documents that are sent to external parties.

Refer to fonts used rather than embedding since that increases file size by three orders of magnitude.

**Comment by clausmullie** [comment]
Replaces our current workaround of keeping templates as google docs, as for example the:
* [expression of interest](https://about.publiccode.net/activities/member-relations/expression-of-interest.html) 
* [information about founding membership](https://about.publiccode.net/activities/member-relations/information-about-founding-membership.html)
* [founding membership proposal](https://about.publiccode.net/activities/member-relations/founding-membership-proposal.html)
